import { Link } from 'react-router-dom';
import { ArrowRight, Mail, MessageSquare, Store } from 'lucide-react';

export default function ContactPage() {
  return <div className="min-h-screen bg-[#f5f2e9] text-[#172014]">
    <header className="border-b border-[#ddd7c8] bg-[#172014] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-lime-400 text-slate-950"><Store size={17}/></span><strong>KampStock</strong></Link><div className="flex items-center gap-3"><Link to="/login" className="rounded-full px-4 py-2 text-sm text-white/75">Sign in</Link><Link to="/register" className="rounded-full bg-lime-400 px-4 py-2 text-sm font-bold text-slate-950">Get started</Link></div></div></header>
    <main><section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">Contact KampStock</p><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] sm:text-7xl">Talk to the people behind the system.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">For product evaluation, onboarding, support, security or partnership questions, use the appropriate channel available to your business.</p></section>
    <section className="border-y border-[#ddd7c8] bg-[#ebe7da]"><div className="mx-auto grid max-w-6xl gap-px bg-[#d8d1c0] md:grid-cols-3">
      {[[Mail,'Business enquiries','For product evaluation, onboarding and commercial questions.'],[MessageSquare,'Existing customers','Use your established support channel so account context can be verified safely.'],[Store,'Security reports','Report suspected weaknesses privately. Never publish credentials or customer data.']].map(([Icon,title,text])=><article key={String(title)} className="bg-[#f5f2e9] p-8 sm:p-10"><Icon className="text-orange-600" size={25}/><h2 className="mt-6 text-xl font-extrabold">{String(title)}</h2><p className="mt-2 leading-7 text-slate-600">{String(text)}</p></article>)}
    </div></section>
    <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><div className="rounded-[2rem] bg-[#172014] p-8 text-white sm:p-12"><p className="text-xs font-black uppercase tracking-[0.2em] text-lime-400">Ready to start?</p><h2 className="mt-3 max-w-2xl text-3xl font-black sm:text-4xl">See how KampStock fits the way your business already works.</h2><div className="mt-7 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center rounded-full bg-lime-400 px-6 py-3.5 text-sm font-extrabold text-slate-950">Create a business <ArrowRight className="ml-2" size={16}/></Link><Link to="/how-it-works" className="inline-flex items-center rounded-full border border-white/20 px-6 py-3.5 text-sm font-bold text-white">How it works</Link></div></div></section></main>
    <footer className="border-t border-[#ddd7c8] px-5 py-8 text-center text-xs text-slate-500">© {new Date().getFullYear()} KampStock · Created by Perez Chris · <Link to="/privacy">Privacy</Link> · <Link to="/terms">Terms</Link> · <Link to="/security">Security</Link></footer>
  </div>;
}