import { Link } from 'react-router-dom';
import { ArrowRight, Database, LockKeyhole, ShieldCheck, Store } from 'lucide-react';

const controls = [
 ['Tenant isolation', 'Business data is scoped to the authenticated tenant boundary throughout the application architecture.', Database],
 ['Authentication and access', 'Users authenticate into business workspaces and authorization controls separate operational roles and permissions.', LockKeyhole],
 ['Transaction integrity', 'Critical workflows use database transactions and atomic state transitions where concurrent requests could otherwise create duplicate or inconsistent results.', ShieldCheck],
 ['Operational resilience', 'Backups, restore logic, offline POS recovery, error monitoring and automated CI checks are part of the production engineering model.', ShieldCheck],
];

export default function SecurityPage() {
 return <div className="min-h-screen bg-[#f5f2e9] text-[#172014]"><header className="border-b border-[#ddd7c8] bg-[#172014] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-lime-400 text-slate-950"><Store size={17}/></span><strong>KampStock</strong></Link><Link to="/register" className="rounded-full bg-lime-400 px-4 py-2 text-sm font-bold text-slate-950">Get started</Link></div></header><main><section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">Security & reliability</p><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] sm:text-7xl">Business software should protect the record it creates.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">KampStock is engineered around tenant boundaries, controlled access, transactional consistency and operational recovery. Security claims are intentionally limited to controls implemented in the product.</p></section><section className="border-y border-[#ddd7c8] bg-[#ebe7da]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="grid gap-px overflow-hidden rounded-3xl border border-[#d8d1c0] bg-[#d8d1c0] md:grid-cols-2">{controls.map(([title,text,Icon])=><article key={String(title)} className="bg-[#f5f2e9] p-8 sm:p-10"><Icon className="text-orange-600" size={25}/><h2 className="mt-6 text-xl font-extrabold">{String(title)}</h2><p className="mt-2 leading-7 text-slate-600">{String(text)}</p></article>)}</div></div></section><section className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="rounded-[2rem] bg-[#172014] p-8 text-white sm:p-12"><p className="max-w-3xl text-sm leading-7 text-white/65">Production security also depends on infrastructure configuration, secrets management, provider controls, backups, monitoring and the business's own operational practices. External certifications or regulatory approvals are not implied by this page.</p><Link to="/privacy" className="mt-7 inline-flex items-center rounded-full bg-white px-5 py-3 text-sm font-bold text-[#172014]">Read the privacy policy <ArrowRight className="ml-2" size={16}/></Link></div></section></main><footer className="border-t border-[#ddd7c8] px-5 py-8 text-center text-xs text-slate-500">© {new Date().getFullYear()} KampStock · <Link to="/privacy">Privacy</Link> · <Link to="/terms">Terms</Link> · <Link to="/acceptable-use">Acceptable use</Link></footer></div>;
}
